#!/usr/bin/env python3
"""
Compare RDF triples generated by VitalSigns vs data_format_utils processing.
"""

import json
import sys
from pathlib import Path
from rdflib import Graph

# Add the project root to Python path
project_root = Path(__file__).parent.parent
sys.path.insert(0, str(project_root))

from vital_ai_vitalsigns.vitalsigns import VitalSigns
from ai_haley_kg_domain.model.KGEntity import KGEntity

def compare_rdf_triples():
    """Compare RDF triples from VitalSigns vs manual processing."""
    print("🔍 Comparing RDF Triples: VitalSigns vs Manual Processing")
    print("=" * 70)
    
    # Create test object
    entity = KGEntity()
    entity.URI = "http://example.com/test-entity"
    entity.name = "Test Entity"
    
    # Get VitalSigns JSON-LD
    jsonld = entity.to_jsonld()
    
    print("1. VitalSigns JSON-LD Output:")
    print(f"   Contains 'type': {jsonld.get('type', 'NOT FOUND')}")
    print(f"   Contains 'rdf:type': {'http://www.w3.org/1999/02/22-rdf-syntax-ns#type' in jsonld}")
    print(f"   Contains 'vitaltype': {'http://vital.ai/ontology/vital-core#vitaltype' in jsonld}")
    
    # Parse JSON-LD with RDFLib (like data_format_utils does)
    print(f"\n2. Parsing JSON-LD with RDFLib (data_format_utils approach):")
    
    g = Graph()
    jsonld_str = json.dumps(jsonld)
    g.parse(data=jsonld_str, format='json-ld')
    
    # Check what triples are generated
    RDF_TYPE = "http://www.w3.org/1999/02/22-rdf-syntax-ns#type"
    VITALTYPE = "http://vital.ai/ontology/vital-core#vitaltype"
    
    rdf_type_triples = []
    vitaltype_triples = []
    all_triples = []
    
    for s, p, o in g:
        all_triples.append((str(s), str(p), str(o)))
        if str(p) == RDF_TYPE:
            rdf_type_triples.append((str(s), str(p), str(o)))
        elif str(p) == VITALTYPE:
            vitaltype_triples.append((str(s), str(p), str(o)))
    
    print(f"   Total triples parsed: {len(all_triples)}")
    print(f"   rdf:type triples found: {len(rdf_type_triples)}")
    print(f"   vitaltype triples found: {len(vitaltype_triples)}")
    
    print(f"\n3. Triple Details:")
    for i, (s, p, o) in enumerate(all_triples):
        if 'type' in p.lower():
            print(f"   Triple {i}: <{s}> <{p}> <{o}>")
    
    # Show what data_format_utils would do
    print(f"\n4. What data_format_utils.py would do:")
    
    subjects_with_vitaltype = {}
    subjects_with_rdf_type = set()
    
    for s, p, o in all_triples:
        if p == VITALTYPE:
            subjects_with_vitaltype[s] = o
        elif p == RDF_TYPE:
            subjects_with_rdf_type.add(s)
    
    print(f"   Subjects with vitaltype: {len(subjects_with_vitaltype)}")
    print(f"   Subjects with rdf:type: {len(subjects_with_rdf_type)}")
    
    # Check if data_format_utils would add rdf:type
    missing_rdf_type = []
    for subject, vitaltype_uri in subjects_with_vitaltype.items():
        if subject not in subjects_with_rdf_type:
            missing_rdf_type.append((subject, vitaltype_uri))
    
    if missing_rdf_type:
        print(f"   ❌ data_format_utils would ADD {len(missing_rdf_type)} rdf:type triples:")
        for s, o in missing_rdf_type:
            print(f"      <{s}> <{RDF_TYPE}> <{o}>")
    else:
        print(f"   ✅ No missing rdf:type triples - data_format_utils would NOT modify")

if __name__ == "__main__":
    compare_rdf_triples()
