#!/usr/bin/env python3
"""
Graph Visualization Test Space — Setup Script
==============================================

Creates (or resets) the ``graph_viz_test`` space and imports all six
graph-visualization dataset files (A–F) generated by
``generate_graph_viz_test_data.py``.

Usage:
    python test_scripts/data/setup_graph_viz_test_space.py          # full setup
    python test_scripts/data/setup_graph_viz_test_space.py --keep   # skip delete, import only missing

Requires a running VitalGraph server (reads config from .env / environment).

See: planning/planning_visualization/graph_session_architecture_plan.md §9.8
"""

import asyncio
import argparse
import logging
import sys
import time
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent.parent))

from vitalgraph.client.vitalgraph_client import VitalGraphClient

logging.basicConfig(level=logging.INFO, format="%(message)s")
logger = logging.getLogger(__name__)

# ── Configuration ─────────────────────────────────────────────────────────

SPACE_ID = "graph_viz_test"
GRAPH_ID = "urn:vitalgraph:graph_viz_test:data"

VITAL_FILES = [
    "generated_instances/graph_viz_test_A_people.vital",
    "generated_instances/graph_viz_test_B_research.vital",
    "generated_instances/graph_viz_test_C_supply.vital",
    "generated_instances/graph_viz_test_D_social.vital",
    "generated_instances/graph_viz_test_E_unary.vital",
    "generated_instances/graph_viz_test_F_toplevel.vital",
]


# ── Helpers ───────────────────────────────────────────────────────────────

async def _ensure_idempotent(coro, label: str, *, ignore_errors: bool = False):
    """Run an async call, swallowing 409/already-exists errors."""
    try:
        result = await coro
        logger.info("  Created %s", label)
        return result
    except Exception as e:
        msg = str(e).lower()
        if "409" in str(e) or "already exists" in msg or "duplicate" in msg:
            logger.info("  %s already exists (skipped)", label)
            return None
        if ignore_errors:
            logger.warning("  %s: %s (continuing)", label, e)
            return None
        raise


async def delete_space(client: VitalGraphClient):
    """Delete existing space if present."""
    print("Step 1: Deleting existing space...")
    try:
        resp = await client.spaces.delete_space(SPACE_ID)
        logger.info("  Deleted space '%s': %s", SPACE_ID, getattr(resp, 'message', resp))
    except Exception as e:
        if "404" in str(e) or "not found" in str(e).lower():
            logger.info("  Space '%s' not found (clean start)", SPACE_ID)
        else:
            raise


async def create_space(client: VitalGraphClient):
    """Create fresh space."""
    from vitalgraph.model.spaces_model import Space

    print("Step 2: Creating space...")
    space = Space(
        space=SPACE_ID,
        space_name="Graph Visualization Test",
        space_description="Test space for graph visualization datasets (A–F)",
    )
    await _ensure_idempotent(
        client.spaces.create_space(space),
        f"space '{SPACE_ID}'",
    )


async def import_file(client: VitalGraphClient, vital_path: Path, step_num: int):
    """Import one .vital file into the space."""
    from vitalgraph.model.import_model import ImportJobCreate, ImportMode, FileFormat

    if not vital_path.exists():
        logger.error("  File not found: %s — run generate_graph_viz_test_data.py first", vital_path)
        return False

    print(f"Step {step_num}: Importing {vital_path.name} ({vital_path.stat().st_size / 1024:.0f} KB)...")
    job_create = ImportJobCreate(
        space_id=SPACE_ID,
        graph_uri=GRAPH_ID,
        file_format=FileFormat.VITAL,
        mode=ImportMode.APPEND,
    )
    create_resp = await client.imports.create_import_job(job_create)
    job_id = create_resp.job.job_id
    logger.info("  Import job created: %s", job_id)

    await client.imports.upload_import_file(job_id, str(vital_path))
    logger.info("  File uploaded")

    await client.imports.execute_import_job(job_id)
    logger.info("  Import execution started")

    for _ in range(120):
        status_resp = await client.imports.get_import_status(job_id)
        status_str = str(status_resp.status).lower()
        if 'completed' in status_str or 'done' in status_str:
            logger.info("  Import completed: %s records", status_resp.records_done)
            return True
        if 'failed' in status_str or 'error' in status_str:
            logger.error("  Import failed: %s", status_resp.error_message)
            return False
        await asyncio.sleep(1)

    logger.error("  Import timed out after 120s")
    return False


async def verify_counts(client: VitalGraphClient):
    """Run a simple SPARQL query to verify object counts."""
    from vitalgraph.model.sparql_model import SPARQLQueryRequest

    print("Step 9: Verifying object counts...")
    try:
        request = SPARQLQueryRequest(
            query="""
                SELECT (COUNT(DISTINCT ?s) AS ?total) WHERE {
                    ?s a ?type .
                }
            """,
        )
        result = await client.sparql.execute_sparql_query(SPACE_ID, request)
        logger.info("  Distinct typed subjects: %s", result)
    except Exception as e:
        logger.warning("  Verification query failed: %s (non-fatal)", e)


# ── Main ──────────────────────────────────────────────────────────────────

async def main(keep: bool = False):
    print("=" * 70)
    print("Graph Visualization Test Space — Setup")
    print("=" * 70)
    print(f"  Space: {SPACE_ID}")
    print(f"  Graph: {GRAPH_ID}")
    print(f"  Files: {len(VITAL_FILES)}")
    print()

    client = VitalGraphClient(token_expiry_seconds=300)
    await client.open()

    try:
        if not keep:
            await delete_space(client)
        await create_space(client)

        # Import all dataset files
        success_count = 0
        for i, vital_file in enumerate(VITAL_FILES):
            vital_path = Path(vital_file)
            ok = await import_file(client, vital_path, step_num=3 + i)
            if ok:
                success_count += 1

        print()
        print(f"  Imported {success_count}/{len(VITAL_FILES)} files")

        if success_count == len(VITAL_FILES):
            await verify_counts(client)

    finally:
        await client.close()

    print()
    if success_count == len(VITAL_FILES):
        print("✅ Setup complete — all datasets imported into space '%s'" % SPACE_ID)
    else:
        print("⚠️  Setup completed with errors — %d/%d files imported" % (success_count, len(VITAL_FILES)))
        sys.exit(1)


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Setup graph_viz_test space with test datasets")
    parser.add_argument("--keep", action="store_true",
                        help="Keep existing space, only add missing data")
    args = parser.parse_args()
    asyncio.run(main(keep=args.keep))
