#!/usr/bin/env python3
"""
Customer Journey Event Timeline — Space Setup Script
=====================================================

Creates (or resets) the ``customer_journey_test`` space and imports the
customer journey event dataset generated by
``generate_customer_journey_events.py``.

Usage:
    python test_scripts/data/setup_customer_journey_space.py          # full setup
    python test_scripts/data/setup_customer_journey_space.py --keep   # skip delete

Requires a running VitalGraph server (reads config from .env / environment).

See: planning/planning_ui/event_timeline_visualization_plan.md
"""

import asyncio
import argparse
import logging
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent.parent))

from vitalgraph.client.vitalgraph_client import VitalGraphClient

logging.basicConfig(level=logging.INFO, format="%(message)s")
logger = logging.getLogger(__name__)

# ── Configuration ─────────────────────────────────────────────────────────

SPACE_ID = "customer_journey_test"
GRAPH_ID = "urn:graph:journey_onboarding_demo_001"

VITAL_FILE = "generated_instances/customer_journey_events_v3.vital"


# ── Helpers ───────────────────────────────────────────────────────────────

async def _ensure_idempotent(coro, label: str, *, ignore_errors: bool = False):
    """Run an async call, swallowing 409/already-exists errors."""
    try:
        result = await coro
        logger.info("  Created %s", label)
        return result
    except Exception as e:
        msg = str(e).lower()
        if "409" in str(e) or "already exists" in msg or "duplicate" in msg:
            logger.info("  %s already exists (skipped)", label)
            return None
        if ignore_errors:
            logger.warning("  %s: %s (continuing)", label, e)
            return None
        raise


async def delete_space(client: VitalGraphClient):
    """Delete existing space if present."""
    print("Step 1: Deleting existing space...")
    try:
        resp = await client.spaces.delete_space(SPACE_ID)
        logger.info("  Deleted space '%s': %s", SPACE_ID, getattr(resp, 'message', resp))
    except Exception as e:
        if "404" in str(e) or "not found" in str(e).lower():
            logger.info("  Space '%s' not found (clean start)", SPACE_ID)
        else:
            raise


async def create_space(client: VitalGraphClient):
    """Create fresh space."""
    from vitalgraph.model.spaces_model import Space

    print("Step 2: Creating space...")
    space = Space(
        space=SPACE_ID,
        space_name="Customer Journey Test",
        space_description="Test space for event timeline visualization — customer onboarding journey",
    )
    await _ensure_idempotent(
        client.spaces.create_space(space),
        f"space '{SPACE_ID}'",
    )


async def import_file(client: VitalGraphClient, vital_path: Path):
    """Import the .vital file into the space."""
    from vitalgraph.model.import_model import ImportJobCreate, ImportMode, FileFormat

    if not vital_path.exists():
        print(f"  ERROR: File not found: {vital_path}")
        print("  Run generate_customer_journey_events.py first.")
        sys.exit(1)

    print(f"Step 3: Importing {vital_path.name} ({vital_path.stat().st_size / 1024:.0f} KB)...")
    job_create = ImportJobCreate(
        space_id=SPACE_ID,
        graph_uri=GRAPH_ID,
        file_format=FileFormat.VITAL,
        mode=ImportMode.APPEND,
    )
    create_resp = await client.imports.create_import_job(job_create)
    job_id = create_resp.job.job_id
    logger.info("  Import job created: %s", job_id)

    await client.imports.upload_import_file(job_id, str(vital_path))
    logger.info("  File uploaded")

    await client.imports.execute_import_job(job_id)
    logger.info("  Import execution started")

    for _ in range(60):
        status_resp = await client.imports.get_import_status(job_id)
        status_str = str(status_resp.status).lower()
        if 'completed' in status_str or 'done' in status_str:
            logger.info("  Import completed: %s records", status_resp.records_done)
            return
        if 'failed' in status_str or 'error' in status_str:
            logger.error("  Import failed: %s", status_resp.error_message)
            sys.exit(1)
        await asyncio.sleep(1)

    logger.error("  Import timed out after 60s")
    sys.exit(1)


async def main_async(keep: bool = False):
    """Main setup flow."""
    print("=" * 70)
    print("Customer Journey Event Timeline — Space Setup")
    print("=" * 70)
    print(f"  Space: {SPACE_ID}")
    print(f"  Graph: {GRAPH_ID}")
    print()

    client = VitalGraphClient(token_expiry_seconds=300)
    await client.open()

    try:
        if not keep:
            await delete_space(client)

        await create_space(client)

        # Resolve vital file path
        repo_root = Path(__file__).resolve().parent.parent.parent
        vital_path = repo_root / VITAL_FILE

        await import_file(client, vital_path)

    finally:
        await client.close()

    print(f"\nDone! Space '{SPACE_ID}' ready with graph '{GRAPH_ID}'")
    print("Open the graph viewer, select this space/graph, and use 'Load Entire Space'.")


def main():
    parser = argparse.ArgumentParser(
        description="Setup customer journey test space for event timeline visualization"
    )
    parser.add_argument("--keep", action="store_true",
                        help="Don't delete existing space, just import")
    args = parser.parse_args()
    asyncio.run(main_async(keep=args.keep))


if __name__ == "__main__":
    main()
