"""The synthetic TRAVERSAL fixtures — mixed nodes, mixed edges, real criteria.

Generated by `scripts/generate_graph_dataset.py`. See that script for why the
topology is random rather than a stride rule and why the ground truth is walked
rather than derived.

These exist because neither older fixture can express a filtered traversal:

    wordnet_frames   connection frames, but the only criterion available is the
                     traversal TYPE — every slot is a KGEntitySlot and the space
                     holds no literal values at all
    lead_synth       every comparator and datatype, but ATTRIBUTE frames only:
                     entity -> frame -> literal. Nothing connects two entities,
                     so there is nothing to walk

So "follow edges between entities, several hops, keeping only hops whose frame
satisfies a value criterion" — the thing a graph store is for — could not be
measured on either. `issues/048` has type-filtered numbers for that reason and
no value-filtered ones.

WHAT THE MANIFEST GUARANTEES

`actual_matches` are tallies of what was generated, not what the distributions
imply, so a bench asserts against a number rather than an observation.

`traversal` holds the answer sets: for each sample start, the entities reachable
at EXACTLY depth 1, 2 and 3, unfiltered and under four separate criteria. They
are produced by a BFS over the same edge list the N-Triples are written from,
sharing no code with the SQL pipeline, so a test comparing against them is a
genuine differential rather than a restatement.

Sample starts are chosen, not drawn uniformly: at ~50% selectivity a random
start usually reaches nothing by depth 3, and a fixture whose expected answers
are mostly empty cannot tell a working traversal from one that returns nothing.
Two dead-end starts are kept deliberately.

LOADING

    python scripts/generate_graph_dataset.py --entities 10000 \\
        --out internal_data/graph_synth_10k
    python scripts/convert_nt_to_csv.py internal_data/graph_synth_10k/*.nt \\
        --out test_data/graph_synth_10k.csv --graph urn:sp_graph_synth_10k \\
        --dataset graph_synth
    VG_TEST_PG_PORT=5432 python scripts/load_wordnet_csv.py \\
        --space sp_graph_synth_10k \\
        --quads-csv test_data/graph_synth_10k.csv \\
        --terms-csv test_data/graph_synth_10k_terms.csv

The loader defaults to port 5433 — the docker test stack. Override it when the
space lives on the host cluster, or it truncates and loads a space of the same
name in the other database, which is the hazard its own docstring warns about.
"""

from __future__ import annotations

import json
from pathlib import Path

_ROOT = Path(__file__).resolve().parents[2]

HALEY = "http://vital.ai/ontology/haley-ai-kg#"
VITAL = "http://vital.ai/ontology/vital-core#"
BASE = "urn:graphsyn"

SRC_ROLE = "urn:hasSourceEntity"
DST_ROLE = "urn:hasDestinationEntity"

# The criterion predicates, one per datatype the comparators care about.
SCORE = f"{HALEY}hasScore"          # xsd:integer
WEIGHT = f"{HALEY}hasWeight"        # xsd:double
OCCURRED = f"{HALEY}hasOccurredAt"  # xsd:dateTime
LABEL = f"{HALEY}hasLabel"          # xsd:string
CATEGORY = f"{HALEY}hasCategory"    # xsd:string, weighted — the IN case
ACTIVE = f"{HALEY}hasActive"        # xsd:boolean
TAG = f"{HALEY}hasTag"              # uri, MULTI-VALUED (1-4 per edge)


class GraphFixture:
    """A generated traversal space and the manifest that says what is in it."""

    def __init__(self, space: str, graph: str, label: str, manifest_dir: str):
        self.space = space
        self.graph = graph
        self.label = label
        self.manifest_path = _ROOT / "internal_data" / manifest_dir / "manifest.json"

    def __repr__(self):
        return self.label

    @property
    def available(self) -> bool:
        return self.manifest_path.exists()

    def manifest(self) -> dict:
        """The manifest, or a clear failure. Never a silent default.

        A bench that fell back to defaults would assert against numbers no data
        produced and pass while measuring nothing.
        """
        if not self.available:
            raise FileNotFoundError(
                f"{self.manifest_path} not found — generate it with "
                f"scripts/generate_graph_dataset.py (see this module's docstring)")
        return json.loads(self.manifest_path.read_text())

    def entity_uri(self, index: int) -> str:
        return f"{BASE}:entity:{index}"

    def tag_uri(self, tag: str) -> str:
        return f"{BASE}:tag:{tag}"

    def sample_starts(self) -> list:
        return self.manifest()["traversal"]["sample_starts"]

    def expected(self, key: str, start: int, depth: int) -> set:
        """The entity INDEXES reachable at exactly `depth`, per the manifest.

        `key` selects the walk: "frame_traversal", "relation_traversal",
        "frame_traversal_score_gte_50" and so on — the keys under `traversal`.
        """
        walks = self.manifest()["traversal"]
        if key not in walks:
            raise KeyError(f"{key} not in manifest; have {sorted(walks)}")
        return set(walks[key][str(start)][str(depth)])


SYNTH = [
    GraphFixture("sp_graph_synth_10k", "urn:sp_graph_synth_10k", "10k",
                 "graph_synth_10k"),
    GraphFixture("sp_graph_synth_100k", "urn:sp_graph_synth_100k", "100k",
                 "graph_synth_100k"),
]

SMALL = SYNTH[0]
LARGE = SYNTH[1]


# ---------------------------------------------------------------------------
# Query construction — shared so a bench and a correctness test walk the graph
# the same way
# ---------------------------------------------------------------------------

def frame_hop(n: int, from_var: str, to_var: str, criterion: str = "") -> str:
    """One entity -> frame -> entity hop as its own 6 tables.

    Both slot values stay VARIABLES. `rewrite_frame_entity_table` reads the
    entity from the object variable, so an end pinned to a constant is not
    recognised as a slot group and that hop does not collapse (issues/048).
    Pin the start with FILTER instead.

    `criterion` is a template using {n}: anything it binds must be numbered per
    hop, or one value has to satisfy every hop at once and the query returns
    empty for a reason that has nothing to do with the data.
    """
    return f"""
        ?f{n} a <{HALEY}KGFrame> .
        ?se{n} <{VITAL}hasEdgeSource> ?f{n} .
        ?se{n} <{VITAL}hasEdgeDestination> ?ss{n} .
        ?ss{n} <{HALEY}hasKGSlotType> <{SRC_ROLE}> .
        ?ss{n} <{HALEY}hasEntitySlotValue> {from_var} .
        ?de{n} <{VITAL}hasEdgeSource> ?f{n} .
        ?de{n} <{VITAL}hasEdgeDestination> ?ds{n} .
        ?ds{n} <{HALEY}hasKGSlotType> <{DST_ROLE}> .
        ?ds{n} <{HALEY}hasEntitySlotValue> {to_var} .{criterion.format(n=n)}"""


def relation_hop(n: int, from_var: str, to_var: str, criterion: str = "") -> str:
    """One entity -> entity hop over Edge_hasKGRelation.

    The other traversal shape: no frame, no slots, so `frame_entity` cannot
    apply and the edge table is what has to carry it.
    """
    return f"""
        ?r{n} a <{HALEY}Edge_hasKGRelation> .
        ?r{n} <{VITAL}hasEdgeSource> {from_var} .
        ?r{n} <{VITAL}hasEdgeDestination> {to_var} .{criterion.format(n=n)}"""


def chain_query(fx: GraphFixture, start: int, depth: int, *,
                criterion: str = "", hop=frame_hop) -> str:
    """Follow `depth` hops from `start`, projecting the far end."""
    hops = "".join(hop(i + 1, f"?e{i}", f"?e{i + 1}", criterion)
                   for i in range(depth))
    return f"""
    SELECT DISTINCT ?e{depth} WHERE {{ GRAPH <{fx.graph}> {{
        {hops}
        FILTER(?e0 = <{fx.entity_uri(start)}>)
    }} }}"""


# Criterion templates, one per datatype. Each is paired with the manifest key
# holding the answers for that same filter, so a test cannot compare a query
# against the wrong ground truth.
CRITERIA = {
    "score_gte_50": (
        f'\n        ?f{{n}} <{SCORE}> ?sc{{n}} . FILTER(?sc{{n}} >= 50)',
        "frame_traversal_score_gte_50"),
    "category_in_alpha_beta": (
        f'\n        ?f{{n}} <{CATEGORY}> ?ct{{n}} . '
        f'FILTER(?ct{{n}} IN ("alpha", "beta"))',
        "frame_traversal_category_in_alpha_beta"),
    "occurred_second_half": (
        f'\n        ?f{{n}} <{OCCURRED}> ?oc{{n}} . '
        f'FILTER(?oc{{n}} >= "2024-07-01T00:00:00+00:00"'
        f'^^<http://www.w3.org/2001/XMLSchema#dateTime>)',
        "frame_traversal_occurred_second_half"),
}


def entity_indexes(rows) -> set:
    """Entity INDEXES from result rows, whatever the generated column names are."""
    prefix = f"{BASE}:entity:"
    out = set()
    for r in rows:
        for v in r.values():
            if isinstance(v, str) and v.startswith(prefix):
                out.add(int(v[len(prefix):]))
    return out
