"""Shared definitions of the lead fixtures the KGQuery benches run against.

Both the SQL-level bench (`test_kgquery_growth_curve.py`) and the API-level one
(`test_lead_kgquery_bench.py`) measure the same queries against the same spaces
— one through the generated SQL, one through the running service. They have to
agree on what those spaces are, or a comparison between the two layers is
comparing different data without saying so.

Sizes are deliberately plural. One fixture gives a cost at a single scale; two
show how it *moves* with scale, which is the property that matters after the
range push-down: the pre-push-down cost tracked the candidate set, so the gap
should widen with entity count rather than stay put.

Generated by `scripts/generate_lead_dataset.py`; see that script for how the
value distributions are chosen so threshold sweeps vary match count while the
dataset stays fixed.
"""

from __future__ import annotations

from pathlib import Path

_ROOT = Path(__file__).resolve().parents[2]


class LeadFixture:
    """A lead fixture: its space, graph, and manifest of exact match counts.

    `manifest_dir` is relative to internal_data/. The manifest must be the one
    written alongside THIS space's data — its counts are the ground truth every
    assertion uses, so a mismatched pair compares against the wrong numbers
    without complaining.

    `synthetic` marks the generated fixtures. The real 100-entity dataset has no
    manifest and no controlled selectivity, so it is usable for API latency but
    not for the growth curve.
    """

    def __init__(self, space, graph, label, manifest_dir=None, synthetic=True):
        self.space = space
        self.graph = graph
        self.label = label
        self.synthetic = synthetic
        self.manifest_path = (
            _ROOT / "internal_data" / manifest_dir / "manifest.json"
            if manifest_dir else None)

    def __repr__(self):
        return self.label


# The real lead dataset — 100 entities of production-shaped data. Too small to
# separate the cost models, but it is the only non-generated one, so it keeps
# the benches honest about whether the synthetic fixtures behave like real data.
REAL = LeadFixture("sp_sql_lead_dataset", "urn:sql_lead_dataset", "real100",
                   synthetic=False)

SYNTH = [
    LeadFixture("sp_lead_synth_10k", "urn:lead_synth_10k", "10k", "lead_synth"),
    LeadFixture("sp_lead_synth_100k", "urn:lead_synth_100k", "100k",
                "lead_synth_100k"),
]

# A small fixture whose entities carry DUPLICATE ANCHOR QUADS (issues/046).
#
# Every other fixture here is generated by `generate_lead_dataset.py`, which
# emits each triple once — so each entity has exactly one `vitaltype KGEntity`
# row and one `hasKGEntityType` row, and a rewrite that drops the DISTINCT is
# sound on that data no matter how wrong it is in general. That is why the
# semi-join shipped returning 34,659 rows for 34,423 entities on production data
# with every bench green.
#
# Built by `scripts/load_duplicate_quad_dataset.sh`. Deliberately tiny: it
# exists to hold a correctness property, not to measure a cost curve, and it is
# excluded from ALL so no latency bench reports on 500 entities as if that meant
# something.
DUP = LeadFixture("sp_lead_dup", "urn:lead_dup", "dup500", "lead_dup")

# A uniformly DEPTH-1 fixture — entity -> frame -> slot (issues/050).
#
# Every other fixture is uniformly depth 2, because the generator clones
# templates that are. Production is 98% depth 1, so until this existed no
# benchmark ran the dominant shape; all recorded numbers describe the 1.9% case.
#
# Criteria against it must address the frame directly rather than through a
# parent, so a bench using it needs its own depth-1 criteria — the shape matrix
# takes --base-depth for this. Built by scripts/generate_depth_mix_dataset.py.
DEPTH1 = LeadFixture("sp_lead_depth1", "urn:lead_depth1", "depth1", "lead_depth1")

# Everything the API bench can time. The growth curve uses SYNTH only, since it
# needs the manifest.
ALL = [REAL] + SYNTH


async def duplicate_anchor_rows(conn, fx) -> int:
    """Extra rows beyond one per (subject, predicate, object, context).

    A "no duplicates in the result" assertion passes trivially against data that
    has no duplicates to collapse, which is the shape of check that let
    issues/046 through. Tests over DUP call this first and fail loudly at zero
    rather than reporting a green vacuous pass.
    """
    return await conn.fetchval(f"""
        SELECT COALESCE(sum(n) - count(*), 0) FROM (
            SELECT count(*) AS n FROM {fx.space}_rdf_quad
            GROUP BY subject_uuid, predicate_uuid, object_uuid, context_uuid
            HAVING count(*) > 1) x
    """)


# Namespace the bench criteria are written against. A space loaded from an
# older export carries a different namespace, and every criterion then matches
# nothing — which a latency bench would happily report as very fast.
CRITERIA_NS = "urn:acme:kg"


async def require_usable(conn, fx) -> str | None:
    """Return a skip reason if `fx` cannot answer the bench criteria, else None.

    Distinguishes "this fixture is not present/applicable here" from "it is
    present and the query is broken". The first is a skip; the second must stay
    a failure, because a query matching nothing is the exact bug `min_results`
    exists to catch and it looks like a speed-up.
    """
    exists = await conn.fetchval(
        "SELECT 1 FROM pg_tables WHERE schemaname='public' AND tablename=$1",
        f"{fx.space}_rdf_quad")
    if not exists:
        return f"space {fx.space} does not exist"
    if not await conn.fetchval(f"SELECT count(*) FROM {fx.space}_rdf_quad"):
        return f"space {fx.space} exists but is empty — load it first"
    ns_present = await conn.fetchval(
        f"SELECT 1 FROM {fx.space}_term WHERE term_text LIKE $1 LIMIT 1",
        f"{CRITERIA_NS}:slot:%")
    if not ns_present:
        other = await conn.fetchval(
            f"SELECT split_part(term_text, ':slot:', 1) FROM {fx.space}_term "
            f"WHERE term_text LIKE '%:slot:%' LIMIT 1")
        return (f"space {fx.space} uses namespace {other!r}, not "
                f"{CRITERIA_NS!r} — the bench criteria cannot match it")
    return None
