"""Unit tests using real PlanV2 trees from sidecar fixtures.

These tests load JSON fixtures generated by the Jena sidecar (one-time),
reconstruct real PlanV2 trees via map_compile_response() + collect(),
and verify optimizer passes against real-world query shapes.

If no fixtures exist yet, these tests are skipped gracefully.
"""

from __future__ import annotations

import json
from pathlib import Path

import pytest

from vitalgraph.db.jena_sparql.jena_ast_mapper import map_compile_response
from vitalgraph.db.sparql_sql.collect import collect
from vitalgraph.db.sparql_sql.ir import (
    AliasGenerator, PlanV2,
    KIND_BGP, KIND_UNION, KIND_FILTER, KIND_PROJECT,
    RELATION_KINDS, MODIFIER_KINDS,
)
from vitalgraph.db.sparql_sql.var_scope import compute_scope, compute_text_needed_vars
from vitalgraph.db.sparql_sql.filter_pushdown import push_text_filters
from vitalgraph.db.sparql_sql.prune_union import prune_dead_union_branches


FIXTURE_DIR = Path(__file__).resolve().parents[2] / "fixtures" / "plan_trees" / "json"


def _load_fixtures():
    """Load all JSON fixture files, returning (name, fixture_dict) tuples."""
    if not FIXTURE_DIR.exists():
        return []
    fixtures = []
    for path in sorted(FIXTURE_DIR.glob("*.json")):
        data = json.loads(path.read_text())
        fixtures.append((data["name"], data))
    return fixtures


def _build_plan(fixture: dict) -> PlanV2:
    """Reconstruct a PlanV2 from a sidecar fixture."""
    compile_result = map_compile_response(fixture["sidecar_response"])
    aliases = AliasGenerator()
    plan = collect(compile_result.algebra, space_id="test_space", aliases=aliases)
    return plan


FIXTURES = _load_fixtures()

# Skip entire module if no fixtures are generated yet
pytestmark = pytest.mark.skipif(
    len(FIXTURES) == 0,
    reason="No plan tree fixtures found. Run generate_fixtures.py first.",
)


# ---------------------------------------------------------------------------
# Structural invariants — must hold for ALL real queries
# ---------------------------------------------------------------------------

class TestStructuralInvariants:
    """Properties that must hold for every real PlanV2 tree."""

    @pytest.mark.parametrize("name,fixture", FIXTURES, ids=[f[0] for f in FIXTURES])
    def test_plan_builds_without_error(self, name, fixture):
        """collect() should never crash on valid sidecar output."""
        plan = _build_plan(fixture)
        assert plan is not None
        assert plan.kind in RELATION_KINDS | MODIFIER_KINDS

    @pytest.mark.parametrize("name,fixture", FIXTURES, ids=[f[0] for f in FIXTURES])
    def test_all_nodes_have_valid_kind(self, name, fixture):
        """Every node in the tree should have a recognized kind."""
        plan = _build_plan(fixture)
        for node in plan.walk():
            assert node.kind in RELATION_KINDS | MODIFIER_KINDS, (
                f"Unknown kind: {node.kind}"
            )

    @pytest.mark.parametrize("name,fixture", FIXTURES, ids=[f[0] for f in FIXTURES])
    def test_modifier_nodes_have_one_child(self, name, fixture):
        """Modifier nodes should have exactly 1 child."""
        plan = _build_plan(fixture)
        for node in plan.walk():
            if node.is_modifier:
                assert len(node.children) == 1, (
                    f"{node.kind} has {len(node.children)} children, expected 1"
                )

    @pytest.mark.parametrize("name,fixture", FIXTURES, ids=[f[0] for f in FIXTURES])
    def test_leaf_nodes_have_no_children(self, name, fixture):
        """BGP/TABLE/NULL/PATH leaf nodes should have 0 children."""
        plan = _build_plan(fixture)
        for node in plan.walk():
            if node.kind in (KIND_BGP, "table", "null", "path"):
                assert len(node.children) == 0, (
                    f"{node.kind} has {len(node.children)} children, expected 0"
                )


# ---------------------------------------------------------------------------
# Scope invariants
# ---------------------------------------------------------------------------

class TestScopeInvariants:

    @pytest.mark.parametrize("name,fixture", FIXTURES, ids=[f[0] for f in FIXTURES])
    def test_scope_computes_without_error(self, name, fixture):
        """compute_scope should never crash on any real tree."""
        plan = _build_plan(fixture)
        scope = compute_scope(plan)
        assert scope is not None

    @pytest.mark.parametrize("name,fixture", FIXTURES, ids=[f[0] for f in FIXTURES])
    def test_projected_vars_subset_of_visible(self, name, fixture):
        """If the root is a PROJECT, projected vars must be visible in scope."""
        plan = _build_plan(fixture)
        if plan.kind == KIND_PROJECT and plan.project_vars:
            # Compute scope of the child (what's available to project from)
            child_scope = compute_scope(plan.child)
            for var in plan.project_vars:
                assert var in child_scope.all_visible, (
                    f"Projected var '{var}' not visible in child scope. "
                    f"Visible: {child_scope.all_visible}"
                )

    @pytest.mark.parametrize("name,fixture", FIXTURES, ids=[f[0] for f in FIXTURES])
    def test_text_needed_vars_subset_of_bgp_vars(self, name, fixture):
        """text_needed vars should always be a subset of all BGP vars."""
        plan = _build_plan(fixture)
        needed = compute_text_needed_vars(plan)
        # Collect all BGP vars
        all_bgp_vars = set()
        for node in plan.walk():
            if node.kind == KIND_BGP and node.var_slots:
                all_bgp_vars.update(node.var_slots.keys())
        assert needed <= all_bgp_vars, (
            f"text_needed has vars not in any BGP: {needed - all_bgp_vars}"
        )


# ---------------------------------------------------------------------------
# Optimizer safety — optimizers should not crash on real trees
# ---------------------------------------------------------------------------

class TestOptimizerSafety:

    @pytest.mark.parametrize("name,fixture", FIXTURES, ids=[f[0] for f in FIXTURES])
    def test_filter_pushdown_no_crash(self, name, fixture):
        """push_text_filters should not crash on any real tree."""
        plan = _build_plan(fixture)
        # Walk and apply to every FILTER node
        for node in plan.walk():
            if node.kind == KIND_FILTER:
                push_text_filters(node, "test_space")

    @pytest.mark.parametrize("name,fixture", FIXTURES, ids=[f[0] for f in FIXTURES])
    def test_prune_union_no_crash(self, name, fixture):
        """prune_dead_union_branches should not crash on any real tree."""
        compile_result = map_compile_response(fixture["sidecar_response"])
        aliases = AliasGenerator()
        plan = collect(compile_result.algebra, space_id="test_space", aliases=aliases)
        # prune requires aliases context
        prune_dead_union_branches(plan, aliases)
