"""Spaces Model Classes

Pydantic models for space management operations.
"""

from typing import Optional, List
from pydantic import BaseModel, Field

from .api_model import BasePaginatedResponse, BaseCreateResponse, BaseUpdateResponse, BaseDeleteResponse, BaseOperationResponse


class Space(BaseModel):
    """Space model for VitalGraph database.
    
    Represents a graph space that contains RDF data and knowledge graphs.
    Spaces provide logical separation of data within the VitalGraph system.
    """
    id: Optional[int] = Field(
        None, 
        description="Unique space identifier (auto-generated by server)",
        example=1
    )
    tenant: Optional[str] = Field(
        None, 
        description="Tenant identifier for multi-tenant deployments (optional)",
        example="acme_corp"
    )
    space: str = Field(
        ..., 
        description="Space identifier - unique name for the space (required)",
        example="knowledge_base"
    )
    space_name: str = Field(
        ..., 
        description="Human-readable display name for the space (required)",
        example="Knowledge Base"
    )
    space_description: Optional[str] = Field(
        None, 
        description="Detailed description of the space purpose and contents (optional)",
        example="Primary knowledge base containing product information and documentation"
    )
    update_time: Optional[str] = Field(
        None, 
        description="ISO timestamp of last modification (auto-generated by server)",
        example="2025-01-22T00:36:33.214308"
    )
    
    class Config:
        json_schema_extra = {
            "example": {
                "id": 1,
                "tenant": "acme_corp",
                "space": "knowledge_base",
                "space_name": "Knowledge Base",
                "space_description": "Primary knowledge base containing product information and documentation",
                "update_time": "2025-01-22T00:36:33.214308"
            }
        }


class SpacesListResponse(BasePaginatedResponse):
    """Response model for spaces listing operations."""
    spaces: List[Space] = Field(..., description="List of spaces")


class SpaceCreateResponse(BaseCreateResponse):
    """Response model for space creation operations."""
    pass


class SpaceUpdateResponse(BaseUpdateResponse):
    """Response model for space update operations."""
    pass


class SpaceDeleteResponse(BaseDeleteResponse):
    """Response model for space deletion operations."""
    pass


class SpaceOperationResponse(BaseOperationResponse):
    """Response model for general space operations."""
    pass