#!/usr/bin/env bash
# Load the grouped nurture fixture — the 50M+ dataset WITH grouping URIs.
#
# `issues/171`. The existing `lead_nurture_100k` carries zero `hasKGGraphURI`
# triples, so `GroupingURIQueryBuilder.build_complete_entity_graph_query` — the
# query the kgentities and kgframes endpoints actually use to open an entity —
# returns 0 rows against it in 1ms. A load test using the production query would
# have passed every threshold while measuring nothing.
#
# This fixture is generated by the same script with the grouping triples added:
# both levels, matching `set_dual_grouping_uris_with_frame_separation`.
#
#     hasKGGraphURI     the entity, on every object in its graph
#     hasFrameGraphURI  the frame, on the frame and what belongs to it
#
# 74.1M triples at 741.7 per entity, against 534.6 before — grouping is ~2
# triples per subject and there are ~100 subjects in a trimmed entity. It is
# NOT a drop-in replacement for the 53.4M space: absolute quad counts differ,
# and rdf_stats gains two high-cardinality predicates.
#
#   ./scripts/load_lead_nurture_grouped.sh
set -euo pipefail

SPACE="${SPACE:-lead_nurture_grouped}"
GRAPH="${GRAPH:-urn:lead_nurture_grouped}"
OUT_DIR="${OUT_DIR:-internal_data/lead_nurture_grouped}"
CSV="${CSV:-internal_data/lead_nurture_grouped/quads.csv}"

if ! ls "$OUT_DIR"/lead_syn_*.nt >/dev/null 2>&1; then
    echo "▶ 1/4 generate 100k entities (~6 min)"
    python scripts/generate_lead_dataset.py --entities 100000 --trim --seed 7 \
        --out "$OUT_DIR"
else
    echo "▶ 1/4 reusing $OUT_DIR"
fi

echo "▶ 2/4 convert to slim CSV"
python scripts/convert_nt_to_csv.py "$OUT_DIR"/lead_syn_*.nt \
    --out "$CSV" --graph "$GRAPH" --dataset lead_nurture_grouped

echo "▶ 3/4 create space $SPACE"
python - "$SPACE" <<'PY'
import asyncio, os, sys
sys.path.insert(0, os.getcwd())
from scripts.perf_seed_data import ensure_space, pg_params  # noqa: E402
asyncio.run(ensure_space(sys.argv[1], pg_params()))
print(f"   space {sys.argv[1]} ready")
PY

python - "$SPACE" "$GRAPH" <<'PY2'
import asyncio, os, sys
sys.path.insert(0, os.getcwd())
from scripts.perf_seed_data import ensure_graph, pg_params  # noqa: E402
asyncio.run(ensure_graph(sys.argv[1], sys.argv[2], pg_params()))
PY2

echo "▶ 4/4 bulk load"
python scripts/load_wordnet_csv.py --space "$SPACE" \
    --quads-csv "$CSV" --terms-csv "${CSV%.csv}_terms.csv"

echo "✅ $SPACE loaded from $GRAPH"
