#!/usr/bin/env python
"""Build idx_{space}_term_num on existing spaces (issues/040 W4).

New spaces get this from `SparqlSQLSchema.create_space_indexes_sql`; spaces
created before it existed need it added. It is the partial expression index that
serves the numeric range push-down:

    CASE WHEN datatype_id IN (<numeric ids>) AND term_text ~ <num re>
         THEN CAST(term_text AS NUMERIC) END
    WHERE that expression IS NOT NULL

Measured on sp_lead_synth (1.05M terms, `MQLRating >= 99.9`, 16 matches):
24,575 buffers before, 4,396 after — for a 48 kB index, because the partial
predicate keeps it to the numeric literals only.

WITHOUT THE PUSH-DOWN THIS INDEX DOES NOTHING. It was measured at exactly 0.0%
before W2 landed (3,341 buffers before and after, index never referenced),
because the range predicate was applied above the join and nothing ever scanned
the term table by value. Only build it on a deployment that has the push-down.

The DDL is generated by the same function the schema uses, so the indexed
expression cannot drift from the one the push-down emits. That matters more than
it looks: PostgreSQL matches an expression index by comparing normalised
expression trees, so a reordered datatype id list or a different regex costs the
index silently rather than failing.

    python scripts/migrate_term_num_index.py --dsn "..." --dry-run
    python scripts/migrate_term_num_index.py --dsn "..." --space wordnet_frames
    python scripts/migrate_term_num_index.py --dsn "..."            # all spaces
    python scripts/migrate_term_num_index.py --dsn "..." --min-terms 100000

Uses CREATE INDEX CONCURRENTLY, so it does not block writes and cannot run
inside a transaction. A failed CONCURRENTLY build leaves an INVALID index; the
script reports any it finds so they can be dropped before retrying.
"""

from __future__ import annotations

import argparse
import asyncio
import os
import sys
import time

import asyncpg

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from vitalgraph.db.sparql_sql.sparql_sql_schema import (  # noqa: E402
    numeric_term_index_sql)


def _dsn_from_env() -> str:
    return (f"postgresql://{os.environ.get('VG_TEST_PG_USER', 'postgres')}:"
            f"{os.environ.get('VG_TEST_PG_PASSWORD', '')}@"
            f"{os.environ.get('VG_TEST_PG_HOST', 'localhost')}:"
            f"{os.environ.get('VG_TEST_PG_PORT', '5432')}/"
            f"{os.environ.get('VG_TEST_PG_DATABASE', 'sparql_sql_graph')}")


async def find_targets(conn, only_space: str | None):
    """Return [(space_id, term_table, n_terms, has_index)]."""
    rows = await conn.fetch(
        "SELECT tablename FROM pg_tables "
        "WHERE schemaname = 'public' AND tablename LIKE '%\\_term' "
        "ORDER BY tablename")
    out = []
    for r in rows:
        table = r["tablename"]
        space = table[:-len("_term")]
        if only_space and space != only_space:
            continue
        has = await conn.fetchval(
            "SELECT 1 FROM pg_indexes WHERE schemaname='public' "
            "AND indexname = $1", f"idx_{space}_term_num")
        n = await conn.fetchval(
            f'SELECT count(*) FROM "{table}" WHERE term_type = \'L\'')
        out.append((space, table, n, bool(has)))
    return out


async def check_invalid(conn) -> list[str]:
    rows = await conn.fetch(
        "SELECT c.relname FROM pg_index i JOIN pg_class c ON c.oid = i.indexrelid "
        "WHERE NOT i.indisvalid AND c.relname LIKE '%\\_term\\_num'")
    return [r["relname"] for r in rows]


async def run(dsn: str, only_space: str | None, dry_run: bool,
              min_terms: int) -> int:
    conn = await asyncpg.connect(dsn)      # autocommit — CONCURRENTLY needs it
    try:
        db = await conn.fetchval("SELECT current_database()")
        host = await conn.fetchval("SELECT inet_server_addr()::text")
        print(f"target: {db} on {host or 'local socket'}"
              f"{'  [DRY RUN]' if dry_run else ''}\n")

        invalid = await check_invalid(conn)
        if invalid:
            print("⚠️  INVALID indexes from an interrupted run — drop these "
                  "before retrying:")
            for name in invalid:
                print(f"      DROP INDEX CONCURRENTLY {name};")
            return 2

        targets = await find_targets(conn, only_space)
        if not targets:
            print("no *_term tables found"
                  + (f" for space {only_space}" if only_space else ""))
            return 0

        todo = [t for t in targets if not t[3] and t[2] >= min_terms]
        done = [t for t in targets if t[3]]
        small = [t for t in targets if not t[3] and t[2] < min_terms]

        print(f"{len(targets)} space(s): {len(todo)} to build, "
              f"{len(done)} already present, {len(small)} below "
              f"--min-terms={min_terms:,}\n")
        for space, _t, n, _h in done:
            print(f"  ⏭️  {space}: already has idx_{space}_term_num "
                  f"({n:,} literals)")
        for space, _t, n, _h in small:
            print(f"  ⏭️  {space}: {n:,} literals, below threshold")

        for space, table, n, _h in todo:
            sql = numeric_term_index_sql(space, table).replace(
                "CREATE INDEX IF NOT EXISTS",
                "CREATE INDEX CONCURRENTLY IF NOT EXISTS")
            print(f"  ➕ {space}: building idx_{space}_term_num "
                  f"({n:,} literals)")
            if dry_run:
                print(f"    would run: {sql[:120]}…")
                continue
            t0 = time.time()
            await conn.execute(sql)
            await conn.execute(f"ANALYZE {table}")
            size = await conn.fetchval(
                "SELECT pg_size_pretty(pg_relation_size($1::regclass))",
                f"idx_{space}_term_num")
            print(f"    ✅ {space}: built in {time.time() - t0:.1f}s ({size})")

        return 0
    finally:
        await conn.close()


def main() -> int:
    ap = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--dsn", default=None,
                    help="postgresql://... (defaults to VG_TEST_PG_* env)")
    ap.add_argument("--space", default=None, help="only this space")
    ap.add_argument("--dry-run", action="store_true")
    ap.add_argument("--min-terms", type=int, default=0,
                    help="skip spaces with fewer literal terms than this — the "
                         "index cannot pay for itself on a tiny space")
    a = ap.parse_args()
    return asyncio.run(run(a.dsn or _dsn_from_env(), a.space, a.dry_run,
                           a.min_terms))


if __name__ == "__main__":
    sys.exit(main())
