"""
paraphrase-multilingual-MiniLM-L12-v2 local vectorization provider.

Wraps :class:`~vitalgraph.entity_registry.entity_vectorizer.WeaviateLocalVectorizer`,
which replicates Weaviate's t2v-transformers HuggingFaceVectorizer exactly
(NLTK sent_tokenize → AutoModel/AutoTokenizer → masked-mean pooling per
sentence → average across sentences, no normalization).

Use this provider for any vector index whose stored vectors were produced by
this model — including vectors auto-generated by Weaviate — so that search-time
query embeddings land in the same vector space.

Model: sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2 (384 dims).
Note this is a *different* model from the `vitalsigns_onnx` provider's bundled
paraphrase-MiniLM-L3-v2, despite both producing 384 dims.

Configuration (via provider_config JSONB):
    model_name: HuggingFace model id, or a local directory (default: resolved
                by resolve_model_source() below)
    device:     'cuda' | 'mps' | 'cpu' (default: best available)

Offline operation: the Docker image bakes the weights to BAKED_MODEL_DIR with
save_pretrained(), and this provider loads from that directory when present.
A directory load bypasses HuggingFace hub resolution entirely — note that
merely warming the HF cache is NOT sufficient, because AutoTokenizer still
issues a model-info API call that fails under HF_HUB_OFFLINE=1.
"""

import asyncio
import logging
import os
from pathlib import Path
from typing import Any, Dict, List, Optional

from vitalgraph.vectorization.base import VectorizationProvider

logger = logging.getLogger(__name__)

PROVIDER_NAME = "paraphrase_multilingual_minilm_l12_v2"
DEFAULT_MODEL = "sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2"

# hidden_size of DEFAULT_MODEL.
NATIVE_DIMENSIONS = 384

# Where the Dockerfile save_pretrained()s the weights.
BAKED_MODEL_DIR = "/app/models/paraphrase-multilingual-MiniLM-L12-v2"

# Overrides BAKED_MODEL_DIR (e.g. a mounted volume in a non-Docker deployment).
MODEL_PATH_ENV_VAR = "VITALGRAPH_PARAPHRASE_MODEL_PATH"

# Files save_pretrained() must have written for a directory to be loadable.
_REQUIRED_FILES = ("config.json", "tokenizer_config.json")


def _is_usable_model_dir(path: str) -> bool:
    p = Path(path)
    return p.is_dir() and all((p / f).is_file() for f in _REQUIRED_FILES)


def resolve_model_source() -> str:
    """Return the local directory to load from, else the hub model id.

    Precedence: $VITALGRAPH_PARAPHRASE_MODEL_PATH → BAKED_MODEL_DIR → hub id.
    An explicitly configured path that is unusable raises rather than silently
    falling back to a network fetch that will fail (or, worse, succeed and mask
    a broken image build).
    """
    override = os.environ.get(MODEL_PATH_ENV_VAR, "").strip()
    if override:
        if not _is_usable_model_dir(override):
            raise ValueError(
                f"{MODEL_PATH_ENV_VAR}={override!r} is not a usable model "
                f"directory (needs {', '.join(_REQUIRED_FILES)})"
            )
        return override

    if _is_usable_model_dir(BAKED_MODEL_DIR):
        return BAKED_MODEL_DIR

    logger.info(
        "No baked model directory at %s — falling back to the HuggingFace hub "
        "id %r. This requires network access on first load.",
        BAKED_MODEL_DIR, DEFAULT_MODEL,
    )
    return DEFAULT_MODEL


class ParaphraseMultilingualMiniLMProvider(VectorizationProvider):
    """Local vectorization with paraphrase-multilingual-MiniLM-L12-v2.

    Matches Weaviate's text2vec-transformers output for the same model.

    Heavy dependencies (torch/transformers/nltk) are imported lazily on
    construction so that importing the registry stays cheap.
    """

    def __init__(self, model_name: Optional[str] = None, device: Optional[str] = None):
        from vitalgraph.entity_registry.entity_vectorizer import WeaviateLocalVectorizer

        # What we load from: a baked directory when available, else a hub id.
        self._model_source = model_name or resolve_model_source()

        # What we *report*: a filesystem path is an artifact location, not a
        # model identity, and it ends up in the vector index's model_name
        # column.  A directory load is still this model.
        self._model_name_str = (
            DEFAULT_MODEL
            if _is_usable_model_dir(self._model_source)
            else self._model_source
        )

        self._vectorizer = WeaviateLocalVectorizer(
            model_name=self._model_source, device=device,
        )
        self._dim = int(self._vectorizer.dim)
        logger.info(
            f"ParaphraseMultilingualMiniLMProvider initialized: "
            f"model={self._model_name_str}, source={self._model_source}, "
            f"device={self._vectorizer.device}, dims={self._dim}"
        )

    @property
    def dimensions(self) -> int:
        return self._dim

    @property
    def provider_name(self) -> str:
        return PROVIDER_NAME

    @property
    def model_name(self) -> str:
        return self._model_name_str

    @property
    def model_source(self) -> str:
        """The directory or hub id the weights were actually loaded from."""
        return self._model_source

    @classmethod
    def expected_dimensions(cls, config: Dict[str, Any]) -> Optional[int]:
        """384 for this model. None if pointed at some other HuggingFace id,
        whose hidden_size is only knowable by loading it."""
        model = (config or {}).get("model_name")
        if model and model != DEFAULT_MODEL and not _is_usable_model_dir(model):
            return None
        return NATIVE_DIMENSIONS

    @classmethod
    def from_config(cls, config: Dict[str, Any]) -> "ParaphraseMultilingualMiniLMProvider":
        """Create from config dict.

        Optional config keys:
            model_name: HuggingFace id or local directory.  Omit to use the
                        baked directory when present (see resolve_model_source).
            device: str — 'cuda' | 'mps' | 'cpu' (default: best available)
        """
        return cls(
            model_name=config.get("model_name"),
            device=config.get("device"),
        )

    async def vectorize_text(self, text: str) -> List[float]:
        """Vectorize a single text string (offloaded to a thread)."""
        return await asyncio.to_thread(self._vectorize_sync, text)

    async def vectorize_texts(self, texts: List[str]) -> List[List[float]]:
        """Vectorize a batch of texts, preserving input order."""
        if not texts:
            return []
        return await asyncio.to_thread(self._vectorize_batch_sync, texts)

    def _vectorize_sync(self, text: str) -> List[float]:
        return self._vectorizer.vectorize_text(text).tolist()

    def _vectorize_batch_sync(self, texts: List[str]) -> List[List[float]]:
        return [self._vectorizer.vectorize_text(t).tolist() for t in texts]
