#!/usr/bin/env python3
"""Debug: show the SQL generated by emit_update for touch_entity_modification_time."""
import asyncio
import sys
sys.path.insert(0, '/Users/hadfield/Local/vital-git/vital-graph')

import asyncpg
from vitalgraph.db.sparql_sql.emit_update import update_to_sql
from vitalgraph.db.jena_sparql.jena_sidecar_client import AsyncSidecarClient
from vitalgraph.db.jena_sparql.jena_ast_mapper import map_compile_response
from vitalgraph.db.sparql_sql.sparql_sql_space_impl import SparqlCompileCache

SPARQL = """
DELETE {
    GRAPH <urn:test_graph> {
        <http://vital.ai/test/entity1> <http://vital.ai/ontology/vital-core#hasObjectModificationDateTime> ?old_mod .
    }
}
INSERT {
    GRAPH <urn:test_graph> {
        <http://vital.ai/test/entity1> <http://vital.ai/ontology/vital-core#hasObjectModificationDateTime> "2026-04-30T12:00:00+00:00"^^<http://www.w3.org/2001/XMLSchema#dateTime> .
    }
}
WHERE {
    GRAPH <urn:test_graph> {
        OPTIONAL { <http://vital.ai/test/entity1> <http://vital.ai/ontology/vital-core#hasObjectModificationDateTime> ?old_mod . }
    }
}
"""

CONN = {'host': 'localhost', 'port': 5432, 'database': 'sparql_sql_graph', 'user': 'postgres', 'password': ''}


async def main():
    client = AsyncSidecarClient(base_url='http://localhost:7070')
    cache = SparqlCompileCache(maxsize=16)
    raw = await cache.compile(SPARQL, client)
    cr = map_compile_response(raw)
    print(f"update_ops: {len(cr.update_ops)}")
    for op in cr.update_ops:
        print(f"  op type: {type(op).__name__}")
        if hasattr(op, 'delete_quads'):
            print(f"  delete_quads: {len(op.delete_quads)}")
            for dq in op.delete_quads:
                print(f"    s={dq.subject} p={dq.predicate} o={dq.object} g={dq.graph}")
        if hasattr(op, 'insert_quads'):
            print(f"  insert_quads: {len(op.insert_quads)}")
        if hasattr(op, 'where_pattern'):
            print(f"  has_where: {op.where_pattern is not None}")

    pool = await asyncpg.create_pool(**CONN, min_size=1, max_size=2)
    async with pool.acquire() as conn:
        sql = await update_to_sql(
            cr.update_ops, 'space_multi_org_crud_test',
            conn=conn,
        )
    await pool.close()

    print("\n=== Generated SQL ===")
    for i, stmt in enumerate(sql.split(';')):
        s = stmt.strip()
        if s:
            print(f"\n-- Statement {i+1}:")
            print(s)

asyncio.run(main())
